DEPTH = ../../../../..

include $(DEPTH)/make/openclsdkdefs.mk 

####
#
#  Targets
#
####

OPENCL			= 1
SAMPLE_EXE		= 1
INSTALL_TO_PUBLIC       = 1
EXE_TARGET 		= IntroStaticCPPKernel
EXE_TARGET_INSTALL   	= IntroStaticCPPKernel

####
#
#  C/CPP files
#
####

FILES 	= IntroStaticCPPKernel


CLFILES = IntroStaticCPPKernel_Kernels.cl


include $(DEPTH)/make/openclsdkrules.mk 

