DEPTH = ../../../..

include $(DEPTH)/make/openclsdkdefs.mk 

SUBDIRS = GaussianNoise \
	  MatrixMulDouble \
	  SobelFilterImage \
	  HDRToneMapping \
	  URNGNoiseGL \
	  DwtHaar1DCPPKernel \
	  TransferOverlapCPP \
	  EigenValue       \
	  FFT \
	  MersenneTwister \
	  MatrixMultiplicationCPPKernel \
	  CplusplusWrapper\
	  HistogramAtomics \
	  IntroStaticCPPKernel \
	  SoAversusAoS
          
include $(DEPTH)/make/openclsdkrules.mk 

