DEPTH = ../../../../..

include $(DEPTH)/make/openclsdkdefs.mk 

####
#
#  Targets
#
####

OPENCL			= 1
SAMPLE_EXE		= 1
EXE_TARGET 		= CplusplusWrapper
EXE_TARGET_INSTALL   	= CplusplusWrapper

####
#
#  C/CPP files
#
####

FILES 	= CplusplusWrapper
CLFILES	= CplusplusWrapper_Kernels.cl


include $(DEPTH)/make/openclsdkrules.mk 

