DEPTH = ../../../../..

include $(DEPTH)/make/openclsdkdefs.mk 

####
#
#  Targets
#
####

OPENCL			= 1
SAMPLE_EXE		= 1
EXE_TARGET 		= BasicDebug
EXE_TARGET_INSTALL   	= BasicDebug

####
#
#  C/CPP files
#
####

FILES 	= BasicDebug 
CLFILES	= BasicDebug_Kernel.cl BasicDebug_Kernel2.cl

include $(DEPTH)/make/openclsdkrules.mk 

