DEPTH = ../../../../..

include $(DEPTH)/make/openclsdkdefs.mk 

####
#
#  Targets
#
####

OPENCL			= 1
SAMPLE_EXE		= 1
EXE_TARGET 		= HelloWorld
EXE_TARGET_INSTALL   	= HelloWorld

####
#
#  C/CPP files
#
####

FILES 	= HelloWorld
CLFILES	= HelloWorld_Kernel.cl

include $(DEPTH)/make/openclsdkrules.mk 

