DEPTH = ../../..

include $(DEPTH)/make/openclsdkdefs.mk 

SUBDIRS = ArrayVsArrayView      \
          FFT                   \
          GEMM                  \
          MD                    \
          SPMV                  \
          Stencil2D             \
          HelloC++AMP           \
          ParReduction          \
          SimpleMultiGPU        \
          Sort                  \
          ArrayBandwidth        \
          TileStaticStorageBandwidth \
          SyncVsAsyncArrayCopy
          
include $(DEPTH)/make/openclsdkrules.mk
