DEPTH = ../../..

include $(DEPTH)/make/openclsdkdefs.mk 

####
#
#  Targets
#
####

APARAPI			= 1
LIB_DIR_INSTALL   	= $(DEPTH)/TempSDKUtil/lib/

####
#
#  C/CPP files
#
####

include $(DEPTH)/make/openclsdkrules.mk 
